name: tox

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.target }}
    strategy:
      fail-fast: false
      matrix:
        target:
          - ubuntu-18.04
          - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
      - name: do run
        run: |
          pip install -U pip
          pip install tox
          tox -e py38
          #podman run --rm -v "$(pwd):/dmnt" -t ${{ matrix.target }} /dmnt/build.sh
